name: DeathMessages
version: '${project.version}'
main: dev.gteeri.deathmessages.DeathMessages
api-version: '1.21'
author: Gteeri
description: Custom death messages plugin

commands:
  deathmsg:
    description: DeathMessages admin command
    usage: /<command> [reload|toggle]
    permission: deathmessages.admin
    aliases: [dm]

permissions:
  deathmessages.admin:
    description: Access to DeathMessages admin commands
    default: op
